/**
 * @jest-environment jsdom
 */

import { WalletConnectorService, ImportedWalletInfo } from '../services/wallet-connector';
import { SmartWalletClient } from '../services/smart-wallet.client';
import { setupWebAuthnMock } from './mock-webauthn';
import { StrKey, Networks } from '@stellar/stellar-sdk';

describe('WalletConnectorService', () => {
  let client: SmartWalletClient;
  let connectorService: WalletConnectorService;
  const testContractAddress = 'CABC123ABCDEFGHIJKLMNOPQRSTUVWXYZ123456ABCDEFG';

  beforeEach(() => {
    setupWebAuthnMock();
    localStorage.clear();
    client = new SmartWalletClient();
    connectorService = new WalletConnectorService(
      client,
      'https://soroban-testnet.stellar.org',
      Networks.TESTNET
    );
  });

  describe('validateContractAddress', () => {
    it('should reject empty address', () => {
      const error = connectorService.validateContractAddress('');
      expect(error).toBe('Contract address is required');
    });

    it('should reject address not starting with C', () => {
      const error = connectorService.validateContractAddress('GABC123...');
      expect(error).toBe('Contract address must start with "C"');
    });

    it('should reject invalid bech32 format', () => {
      const error = connectorService.validateContractAddress('CINVALID!!!');
      expect(error).toBeDefined();
      expect(error).toContain('Invalid contract address format');
    });

    it('should accept valid contract address format', () => {
      const error = connectorService.validateContractAddress(testContractAddress);
      expect(error).toBeUndefined();
    });

    it('should accept contract addresses generated by StrKey', () => {
      // Generate a valid contract address using StrKey
      const contractId = new Uint8Array(32);
      crypto.getRandomValues(contractId);
      const validAddress = StrKey.encodeContract(contractId);
      
      const error = connectorService.validateContractAddress(validAddress);
      expect(error).toBeUndefined();
    });
  });

  describe('verifyContractExists', () => {
    it('should reject address with invalid format', async () => {
      const result = await connectorService.verifyContractExists('invalid-address');
      expect(result).toBe(false);
    });

    it('should reject address not starting with C', async () => {
      const result = await connectorService.verifyContractExists('GABC123...');
      expect(result).toBe(false);
    });

    it('should validate but not require on-chain existence (format check only)', async () => {
      // For unit tests, we verify the address format is acceptable
      // Full on-chain verification would require a live network
      const result = await connectorService.verifyContractExists(testContractAddress);
      // Should return true or false based on RPC availability, not throw
      expect(typeof result).toBe('boolean');
    });
  });

  describe('isSmartWalletContract', () => {
    it('should return false for non-existent contract', async () => {
      const result = await connectorService.isSmartWalletContract('invalid');
      expect(result).toBe(false);
    });

    it('should return a boolean for valid address format', async () => {
      // This checks the format, actual verification requires network
      const result = await connectorService.isSmartWalletContract(testContractAddress);
      expect(typeof result).toBe('boolean');
    });
  });

  describe('fetchSigners', () => {
    it('should return empty array initially (implementation placeholder)', async () => {
      const signers = await connectorService.fetchSigners(testContractAddress);
      expect(Array.isArray(signers)).toBe(true);
      expect(signers.length).toBe(0);
    });

    it('should not throw on valid contract address', async () => {
      await expect(
        connectorService.fetchSigners(testContractAddress)
      ).resolves.toEqual(expect.any(Array));
    });
  });

  describe('importWallet', () => {
    it('should reject invalid address format', async () => {
      const result = await connectorService.importWallet('invalid-address');
      expect(result.isValid).toBe(false);
      expect(result.errorMessage).toBeDefined();
    });

    it('should include wallet address in result', async () => {
      const result = await connectorService.importWallet(testContractAddress);
      expect(result.address).toBe(testContractAddress);
    });

    it('should attempt verification and return structured result', async () => {
      const result = await connectorService.importWallet(testContractAddress);
      expect(result).toHaveProperty('address');
      expect(result).toHaveProperty('isValid');
      expect(result).toHaveProperty('isSmartWallet');
      expect(result).toHaveProperty('signers');
      expect(result).toHaveProperty('errorMessage');
      expect(Array.isArray(result.signers)).toBe(true);
    });
  });

  describe('connectToWallet', () => {
    it('should reject invalid address', async () => {
      const result = await connectorService.connectToWallet('invalid');
      expect(result).toBe(false);
    });

    it('should return boolean result', async () => {
      // Test with valid format (actual verification requires network)
      const result = await connectorService.connectToWallet(testContractAddress);
      expect(typeof result).toBe('boolean');
    });

    it('should validate address format before attempting connection', async () => {
      const result = await connectorService.connectToWallet('not-a-contract');
      expect(result).toBe(false);
    });
  });

  describe('stored connections', () => {
    it('should initialize with empty connections', () => {
      const connections = connectorService.getStoredConnections();
      expect(Array.isArray(connections)).toBe(true);
    });

    it('should handle corrupt localStorage gracefully', () => {
      localStorage.setItem('smart_wallet_connections', 'not-valid-json{');
      const connections = connectorService.getStoredConnections();
      expect(Array.isArray(connections)).toBe(true);
    });

    it('should remove stored connection', () => {
      // Note: Full testing would require successful storage first
      expect(() => {
        connectorService.removeStoredConnection(testContractAddress);
      }).not.toThrow();
    });
  });

  describe('error handling and edge cases', () => {
    it('should handle network errors gracefully', async () => {
      // Network errors should be caught and reported
      const result = await connectorService.importWallet(testContractAddress);
      expect(result).toHaveProperty('errorMessage');
    });

    it('should handle whitespace in address input', () => {
      const addressWithSpaces = `  ${testContractAddress}  `;
      // The service should handle or reject this appropriately
      const error = connectorService.validateContractAddress(addressWithSpaces);
      // Either validates or rejects, but shouldn't crash
      expect(error === undefined || typeof error === 'string').toBe(true);
    });

    it('should maintain connection storage consistency', () => {
      const connections1 = connectorService.getStoredConnections();
      const connections2 = connectorService.getStoredConnections();
      expect(connections1).toEqual(connections2);
    });
  });
});
