/**
 * @fileoverview Paper Wallet Backup Format
 * @description HTML printable wallet backup format
 * @author Galaxy DevKit Team
 * @version 1.0.0
 */

import { BaseBackupFormat, FormatOptions } from './base-format';
import { EncryptedJsonFormat, EncryptedJsonOptions } from './encrypted-json.format';
import { QRCodeFormat } from './qr-code.format';
import {
  BackupFormat,
  WalletBackupData,
  EncryptedBackup,
  PaperWalletOptions,
} from '../types/backup-types';

export interface PaperWalletBackup {
  html: string;
  encryptedBackup: EncryptedBackup;
  qrDataUrl?: string;
}

export interface PaperWalletFormatOptions extends FormatOptions, PaperWalletOptions, EncryptedJsonOptions {}

export class PaperWalletFormat extends BaseBackupFormat<PaperWalletBackup> {
  readonly format: BackupFormat = 'paper-wallet';

  private encryptedJsonFormat: EncryptedJsonFormat;
  private qrCodeFormat: QRCodeFormat;

  constructor() {
    super();
    this.encryptedJsonFormat = new EncryptedJsonFormat();
    this.qrCodeFormat = new QRCodeFormat();
  }

  async encode(
    data: WalletBackupData,
    password: string,
    options?: PaperWalletFormatOptions
  ): Promise<PaperWalletBackup> {
    const encryptedBackup = await this.encryptedJsonFormat.encode(data, password, {
      kdf: options?.kdf,
      kdfParams: options?.kdfParams,
      label: options?.label,
    });

    let qrDataUrl: string | undefined;
    if (options?.includeQR !== false) {
      qrDataUrl = await this.qrCodeFormat.generateQRFromEncryptedBackup(
        encryptedBackup,
        { size: 200, errorCorrectionLevel: 'H' }
      );
    }

    const theme = options?.theme ?? 'light';
    const includeInstructions = options?.includeInstructions !== false;

    const html = this.generateHTML(data, encryptedBackup, {
      theme,
      includeInstructions,
      qrDataUrl,
    });

    return {
      html,
      encryptedBackup,
      qrDataUrl,
    };
  }

  async decode(
    backup: PaperWalletBackup,
    password: string,
    _options?: PaperWalletFormatOptions
  ): Promise<WalletBackupData> {
    return this.encryptedJsonFormat.decode(backup.encryptedBackup, password);
  }

  validate(backup: PaperWalletBackup): boolean {
    return (
      backup.html !== undefined &&
      backup.html.includes('<!DOCTYPE html>') &&
      backup.encryptedBackup !== undefined &&
      this.encryptedJsonFormat.validate(backup.encryptedBackup)
    );
  }

  private generateHTML(
    data: WalletBackupData,
    encryptedBackup: EncryptedBackup,
    options: {
      theme: 'light' | 'dark';
      includeInstructions: boolean;
      qrDataUrl?: string;
    }
  ): string {
    const { theme, includeInstructions, qrDataUrl } = options;

    const styles = this.getStyles(theme);
    const instructions = includeInstructions ? this.getInstructions() : '';
    const qrSection = qrDataUrl ? this.getQRSection(qrDataUrl) : '';

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Stellar Wallet Backup - ${data.publicKey.substring(0, 8)}...</title>
  <style>${styles}</style>
</head>
<body>
  <div class="container">
    <header>
      <h1>🔐 Stellar Wallet Backup</h1>
      <p class="subtitle">Galaxy DevKit - Secure Paper Wallet</p>
    </header>

    <section class="wallet-info">
      <h2>Wallet Information</h2>
      <div class="info-row">
        <span class="label">Public Key:</span>
        <span class="value mono">${data.publicKey}</span>
      </div>
      <div class="info-row">
        <span class="label">Network:</span>
        <span class="value">${data.network}</span>
      </div>
      <div class="info-row">
        <span class="label">Created:</span>
        <span class="value">${encryptedBackup.metadata.created}</span>
      </div>
      <div class="info-row">
        <span class="label">Backup Version:</span>
        <span class="value">${encryptedBackup.version}</span>
      </div>
      <div class="info-row">
        <span class="label">Encryption:</span>
        <span class="value">${encryptedBackup.encryptionAlgorithm} + ${encryptedBackup.kdf}</span>
      </div>
    </section>

    ${qrSection}

    <section class="backup-data">
      <h2>Encrypted Backup Data</h2>
      <p class="warning">⚠️ Keep this data secure. Anyone with this data and your password can access your wallet.</p>
      <div class="backup-json">
        <pre>${JSON.stringify(encryptedBackup, null, 2)}</pre>
      </div>
    </section>

    ${instructions}

    <footer>
      <p>Generated by Galaxy DevKit on ${new Date().toISOString()}</p>
      <p class="checksum">Checksum: ${encryptedBackup.metadata.checksum}</p>
    </footer>
  </div>

  <script>
    window.onbeforeprint = function() {
      document.body.classList.add('printing');
    };
    window.onafterprint = function() {
      document.body.classList.remove('printing');
    };
  </script>
</body>
</html>`;
  }

  private getStyles(theme: 'light' | 'dark'): string {
    const colors = theme === 'dark'
      ? { bg: '#1a1a2e', text: '#eee', border: '#333', accent: '#4a90d9' }
      : { bg: '#fff', text: '#333', border: '#ddd', accent: '#0066cc' };

    return `
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        background: ${colors.bg};
        color: ${colors.text};
        line-height: 1.6;
        padding: 20px;
      }
      .container {
        max-width: 800px;
        margin: 0 auto;
        border: 2px solid ${colors.border};
        padding: 30px;
        border-radius: 8px;
      }
      header {
        text-align: center;
        margin-bottom: 30px;
        padding-bottom: 20px;
        border-bottom: 1px solid ${colors.border};
      }
      h1 { font-size: 24px; margin-bottom: 5px; }
      h2 { font-size: 18px; margin-bottom: 15px; color: ${colors.accent}; }
      .subtitle { color: #888; font-size: 14px; }
      section { margin-bottom: 30px; }
      .info-row {
        display: flex;
        justify-content: space-between;
        padding: 8px 0;
        border-bottom: 1px dashed ${colors.border};
      }
      .label { font-weight: bold; }
      .value { color: #666; }
      .mono { font-family: 'Courier New', monospace; font-size: 12px; word-break: break-all; }
      .qr-section { text-align: center; }
      .qr-section img { max-width: 200px; border: 4px solid ${colors.border}; padding: 10px; background: white; }
      .backup-json {
        background: #f5f5f5;
        border: 1px solid ${colors.border};
        border-radius: 4px;
        padding: 15px;
        overflow-x: auto;
      }
      .backup-json pre {
        font-family: 'Courier New', monospace;
        font-size: 10px;
        white-space: pre-wrap;
        word-wrap: break-word;
        color: #333;
      }
      .warning {
        background: #fff3cd;
        color: #856404;
        padding: 10px;
        border-radius: 4px;
        margin-bottom: 15px;
        font-size: 14px;
      }
      .instructions { background: #e8f4fd; padding: 20px; border-radius: 4px; }
      .instructions h3 { margin-bottom: 10px; }
      .instructions ol { margin-left: 20px; }
      .instructions li { margin-bottom: 8px; }
      footer {
        text-align: center;
        margin-top: 30px;
        padding-top: 20px;
        border-top: 1px solid ${colors.border};
        font-size: 12px;
        color: #888;
      }
      .checksum { font-family: monospace; font-size: 10px; margin-top: 5px; }
      @media print {
        body { padding: 0; }
        .container { border: none; max-width: 100%; }
        .warning { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
      }
    `;
  }

  private getQRSection(qrDataUrl: string): string {
    return `
    <section class="qr-section">
      <h2>QR Code</h2>
      <p>Scan this QR code with a compatible wallet app to restore your backup.</p>
      <img src="${qrDataUrl}" alt="Backup QR Code" />
    </section>`;
  }

  private getInstructions(): string {
    return `
    <section class="instructions">
      <h3>Restoration Instructions</h3>
      <ol>
        <li><strong>Keep this document secure</strong> - Store it in a safe place, preferably fireproof and waterproof.</li>
        <li><strong>Never share your password</strong> - The backup is encrypted, but anyone with your password can access your funds.</li>
        <li><strong>To restore:</strong> Use Galaxy DevKit CLI or API with the <code>importWalletBackup</code> function.</li>
        <li><strong>Verify the checksum</strong> - Before restoring, verify the checksum matches to ensure data integrity.</li>
        <li><strong>Make multiple copies</strong> - Consider storing copies in different secure locations.</li>
      </ol>
    </section>`;
  }
}
