/**
 * @fileoverview Liquidity Pools module exports
 * @description Public API exports for liquidity pool operations
 * @author Galaxy DevKit Team
 * @version 1.0.0
 * @since 2024-01-22
 */

// Export types
export type {
  LiquidityPool,
  LiquidityPoolDeposit,
  LiquidityPoolWithdraw,
  QueryPoolsParams,
  LiquidityPoolResult,
  PoolAnalytics,
  PriceImpact,
  DepositEstimate,
  WithdrawEstimate,
  PoolShare,
  PoolTrade,
} from './types';

// Export manager
export { LiquidityPoolManager } from './liquidity-pool-manager';

// Export calculation functions
export {
  calculateConstantProduct,
  calculateSpotPrice,
  calculateDepositShares,
  calculateWithdrawAmounts,
  calculatePriceImpact,
  calculateSwapOutput,
  estimateDeposit,
  estimateWithdraw,
  calculateMinimumAmounts,
  calculatePriceBounds,
} from './calculations';

// Export validation functions
export {
  validatePoolId,
  validateAmount,
  validateSlippage,
  validatePrice,
  validatePublicKey,
  validateDepositParams,
  validateWithdrawParams,
  validateSufficientShares,
  validateMinimumLiquidity,
} from './validation';

// Export helper functions
export {
  calculateOptimalDeposit,
  formatPoolAssets,
  calculateShareValue,
  wouldImpactPrice,
  calculateBreakEvenPrice,
  calculateImpermanentLoss,
  hasSufficientLiquidity,
  calculateAPRFromFees,
  toStellarPrecision,
  assetsEqual,
  sortAssets,
} from './helpers';

// Note: Pool IDs are generated by the Stellar network and retrieved via Horizon API.
// Use LiquidityPoolManager.queryPools() or getPoolsForAssets() to find pools for specific assets.
